default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  user: postgres
  password: postgres

development:
  <<: *default
  database: rails5-base-project-dev

test:
  <<: *default
  database: rails5-base-project-test

production:
  <<: *default
  database: <%= ENV['APP_DATABASE_NAME'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
